/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendatecnologica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author patriciaaguayo
 */
public class InterfazInfoProducto extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInfoProducto
     */
    public InterfazInfoProducto() {
        initComponents();
    }
    
    public void setProducto(Producto productoSeleccionado) {
        
        Nombre.setText(productoSeleccionado.getNombre());
        Precio.setText(productoSeleccionado.getPrecio() + " €");
        Descripcion.setText(productoSeleccionado.getDescripcion());
       
        // Configurar la salida de características cambiando comas con saltos de línea y poner en mayuscula la primera letra de cada línea
        
        String caracteristicasOriginal = productoSeleccionado.getCaracteristicas();
        String[] lineas = caracteristicasOriginal.split(","); // Dividir por comas

        StringBuilder caracteristicasFormateadas = new StringBuilder("\n"); // StringBuilder para construir la salida del texto

        for (int i = 0; i < lineas.length; i++) {
            String linea = lineas[i].trim(); 
            if (!linea.isEmpty()) {
                
                // Poner en mayúsucla la primera letra
                
                caracteristicasFormateadas.append(Character.toUpperCase(linea.charAt(0)))
                                          .append(linea.substring(1));

                // Agregar salto de línea solo si no es la última línea para que no haya espacio excesivo por abajo               
   
                
                if (i < lineas.length - 1) {
                    caracteristicasFormateadas.append("\n\n");
                }
            }
        }

        Caracteristicas.setText(caracteristicasFormateadas.toString()); 
        
        Cantidad.setText(String.valueOf(productoSeleccionado.getCantidad()));

        // Configurar las imágenes 1 y 2
        
        if (productoSeleccionado.getImagenUrl1() != null) {
            Imagen1.setIcon(new ImageIcon(productoSeleccionado.getImagenUrl1()));
        
        } else {
            Imagen1.setIcon(null);
        }

        if (productoSeleccionado.getImagenUrl2() != null) {
            Imagen2.setIcon(new ImageIcon(productoSeleccionado.getImagenUrl2()));
            System.out.println(productoSeleccionado.getImagenUrl2());
        
        } else {
            Imagen2.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogoI = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Imagen1 = new javax.swing.JLabel();
        Imagen2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        tDescripcion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Caracteristicas = new javax.swing.JTextArea();
        BotonVolverI = new javax.swing.JButton();
        Descripcion = new javax.swing.JLabel();
        tStock = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        LogoI.setIcon(new javax.swing.ImageIcon("/Users/patriciaaguayo/Desktop/Tienda/TiendaTecnologica_AguayoEscuderoPatricia/TiendaTecnologica/src/main/Resources/LogoTienda3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(LogoI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(LogoI)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        Imagen1.setIcon(new javax.swing.ImageIcon("/Users/patriciaaguayo/Desktop/Tienda/TiendaTecnologica_AguayoEscuderoPatricia/TiendaTecnologica/src/main/Resources/Funkos/mickey1.png")); // NOI18N

        Imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Funkos/mickey2.png"))); // NOI18N

        Nombre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Nombre.setText("A");

        Precio.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        Precio.setForeground(new java.awt.Color(102, 102, 102));
        Precio.setText("A");

        tDescripcion.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tDescripcion.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setText("Características:");

        Caracteristicas.setColumns(20);
        Caracteristicas.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        Caracteristicas.setRows(5);
        jScrollPane1.setViewportView(Caracteristicas);

        BotonVolverI.setBackground(new java.awt.Color(0, 0, 0));
        BotonVolverI.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        BotonVolverI.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolverI.setText("Volver");
        BotonVolverI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVolverIMouseClicked(evt);
            }
        });
        BotonVolverI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverIActionPerformed(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        Descripcion.setText("A");

        tStock.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tStock.setText("Stock:");

        Cantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Cantidad.setText("A");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(BotonVolverI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(Imagen1)
                .addGap(77, 77, 77)
                .addComponent(Imagen2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tStock)
                                .addGap(18, 18, 18)
                                .addComponent(Cantidad))
                            .addComponent(Precio)
                            .addComponent(Nombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tDescripcion)
                                .addGap(18, 18, 18)
                                .addComponent(Descripcion)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BotonVolverI, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Imagen2)
                            .addComponent(Imagen1))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addGap(30, 30, 30)
                        .addComponent(Precio)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tDescripcion)
                            .addComponent(Descripcion))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tStock)
                    .addComponent(Cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVolverIActionPerformed

    private void BotonVolverIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverIMouseClicked
       
        InterfazProductos productos = productos = new InterfazProductos();     
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverIMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        InterfazInicio inicio = null;
        
        try {
            
            inicio = new InterfazInicio();
            
        } catch (Exception ex) {
            Logger.getLogger(InterfazProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInfoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInfoProducto().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolverI;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextArea Caracteristicas;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel LogoI;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tDescripcion;
    private javax.swing.JLabel tStock;
    // End of variables declaration//GEN-END:variables

}
